#!/usr/bin/env bash
#
# xboard-node one-line installer (with cert fingerprint reporting patch)
# Repo: https://github.com/pandanetworkgroup/xboard-node-key
#
# One-line install (recommended):
#   curl -fsSL https://raw.githubusercontent.com/pandanetworkgroup/xboard-node-key/main/install.sh \
#     | sudo bash -s -- --mode machine --panel 'https://node.example.com' \
#                          --token 'machine_token_here' --machine-id 1
#
# Interactive install (download first):
#   curl -fsSL https://raw.githubusercontent.com/pandanetworkgroup/xboard-node-key/main/install.sh -o install.sh
#   sudo bash install.sh
#
set -euo pipefail

# ==================== Constants ====================
REPO="pandanetworkgroup/xboard-node-key"
INSTALL_DIR="/etc/xboard-node"
BIN_PATH="/usr/local/bin/xboard-node"
SERVICE_FILE="/etc/systemd/system/xboard-node.service"
SCRIPT_VERSION="1.0.0"

DEF_HEALTH_PORT=65530
DEF_KERNEL="singbox"
DEF_LOG_LEVEL="info"

# ==================== Logging ====================
if [ -t 2 ]; then
    C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_OFF=$'\033[0m'
else
    C_GREEN=''; C_YELLOW=''; C_RED=''; C_OFF=''
fi
log()  { printf '%s[install]%s %s\n' "$C_GREEN"  "$C_OFF" "$*"; }
warn() { printf '%s[warn]%s %s\n'    "$C_YELLOW" "$C_OFF" "$*" >&2; }
die()  { printf '%s[error]%s %s\n'   "$C_RED"    "$C_OFF" "$*" >&2; exit 1; }

# ==================== Args ====================
MODE=""
PANEL_URL=""
TOKEN=""
MACHINE_ID=""
INSTANCE_ID_OVERRIDE=""
HEALTH_PORT=""
KERNEL=""
LOG_LEVEL=""
FORCE=0
SKIP_DOWNLOAD=0

usage() {
    cat <<'USAGE_EOF'
xboard-node one-line installer (cert-fingerprint patched)

One-line install:
  curl -fsSL https://raw.githubusercontent.com/pandanetworkgroup/xboard-node-key/main/install.sh \
    | sudo bash -s -- --mode machine --panel 'https://node.example.com' \
                         --token 'xxx' --machine-id 1

Interactive install:
  sudo bash install.sh
  sudo bash install.sh --help

Args:
  --mode machine          config mode (only machine supported now)
  --panel URL             panel URL (e.g. https://node.178278.xyz)
  --token TOKEN           machine token exported from panel
  --machine-id N          machine id in panel (numeric)
  --instance-id ID        custom instance_id (auto-generated by default)
  --health-port PORT      health check port (default 65530)
  --kernel TYPE           singbox or xray (default singbox)
  --log-level LEVEL       info / warn / error / debug (default info)
  --force                 force overwrite existing config.yml
  --skip-download         skip binary download, reuse /usr/local/bin/xboard-node
  -h, --help              show this help
USAGE_EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --mode)          MODE="$2"; shift 2 ;;
        --panel)         PANEL_URL="$2"; shift 2 ;;
        --token)         TOKEN="$2"; shift 2 ;;
        --machine-id)    MACHINE_ID="$2"; shift 2 ;;
        --instance-id)   INSTANCE_ID_OVERRIDE="$2"; shift 2 ;;
        --health-port)   HEALTH_PORT="$2"; shift 2 ;;
        --kernel)        KERNEL="$2"; shift 2 ;;
        --log-level)     LOG_LEVEL="$2"; shift 2 ;;
        --force)         FORCE=1; shift ;;
        --skip-download) SKIP_DOWNLOAD=1; shift ;;
        -h|--help)       usage; exit 0 ;;
        --)              shift; break ;;
        *)               die "unknown arg: $1 (use --help for usage)" ;;
    esac
done

# ==================== Root check ====================
[ "$(id -u)" -eq 0 ] || die "please run as root (or with sudo)"

# ==================== Interactive prompts ====================
NEED_INTERACTIVE=0
[ -z "$MODE" ]        && NEED_INTERACTIVE=1
[ -z "$PANEL_URL" ]   && NEED_INTERACTIVE=1
[ -z "$TOKEN" ]       && NEED_INTERACTIVE=1
[ -z "$MACHINE_ID" ]  && NEED_INTERACTIVE=1

if [ $NEED_INTERACTIVE -eq 1 ]; then
    if [ ! -t 0 ]; then
        die "interactive mode requires a TTY. when piping via curl|bash, all required args must be supplied. to use interactive mode, download the script first: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh -o install.sh && sudo bash install.sh"
    fi
    log "interactive mode"
    MODE="machine"
    [ -z "$PANEL_URL" ]  && read -rp "panel URL (with https://): " PANEL_URL
    [ -z "$TOKEN" ]      && read -rp "machine token: " TOKEN
    [ -z "$MACHINE_ID" ] && read -rp "machine id (numeric): " MACHINE_ID
fi

[ -z "$HEALTH_PORT" ] && HEALTH_PORT=$DEF_HEALTH_PORT
[ -z "$KERNEL" ]      && KERNEL=$DEF_KERNEL
[ -z "$LOG_LEVEL" ]   && LOG_LEVEL=$DEF_LOG_LEVEL

# ==================== Basic validation ====================
[ "$MODE" = "machine" ] || die "only --mode machine is supported"
[[ "$PANEL_URL" =~ ^https?://[a-zA-Z0-9.:-]+ ]] || die "invalid panel URL (must start with http(s)://)"
[[ "$MACHINE_ID" =~ ^[0-9]+$ ]] || die "machine-id must be numeric"
[ -n "$TOKEN" ] || die "token cannot be empty"

# ==================== Auto instance_id ====================
if [ -z "$INSTANCE_ID_OVERRIDE" ]; then
    panel_host=$(echo "$PANEL_URL" | sed -E 's#^https?://##; s#/.*$##; s#:.*$##')
    clean_host=$(echo "$panel_host" | tr '.' '-')
    hash_input="${MACHINE_ID}|${PANEL_URL}|${TOKEN}"
    if command -v sha256sum >/dev/null 2>&1; then
        h=$(printf '%s' "$hash_input" | sha256sum | cut -c1-6)
    elif command -v shasum >/dev/null 2>&1; then
        h=$(printf '%s' "$hash_input" | shasum -a 256 | cut -c1-6)
    else
        h=$(printf '%s' "$hash_input" | openssl dgst -sha256 -hex 2>/dev/null | grep -oE '[0-9a-f]{6}' | head -1)
    fi
    [ -n "$h" ] || die "cannot compute instance hash (need sha256sum / shasum / openssl)"
    INSTANCE_ID="node-${clean_host}-machine-${MACHINE_ID}-${h}"
else
    INSTANCE_ID="$INSTANCE_ID_OVERRIDE"
fi
TOKEN_ENV_NAME="INSTANCE_$(echo "$INSTANCE_ID" | tr '[:lower:]' '[:upper:]' | tr '-' '_')_MACHINE_TOKEN"

log "instance_id:  $INSTANCE_ID"
log "token_env:    $TOKEN_ENV_NAME"

# ==================== Existing deployment detect ====================
SKIP_CONFIG=0
if [ -f "$INSTALL_DIR/config.yml" ] && [ $FORCE -eq 0 ]; then
    log "existing config.yml found -> upgrade mode (binary only, keep config)"
    SKIP_CONFIG=1
else
    log "fresh deployment"
fi

# ==================== Directories ====================
mkdir -p "$INSTALL_DIR/instances" "$INSTALL_DIR/backups"
chmod 700 "$INSTALL_DIR"

# ==================== Download binary ====================
TS=$(date +%Y%m%d%H%M%S)
if [ $SKIP_DOWNLOAD -eq 0 ]; then
    log "querying latest release..."
    REL_JSON=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null || true)
    ASSET_URL=$(echo "$REL_JSON" | grep -oE '"browser_download_url":[[:space:]]*"[^"]+"' \
                | grep -E 'linux-amd64' | head -1 | sed -E 's/.*"([^"]+)"$/\1/')
    [ -n "$ASSET_URL" ] || die "no linux-amd64 asset found in releases of $REPO. create a release and upload the binary first."

    log "downloading: $ASSET_URL"
    tmp_dl=$(mktemp)
    curl -fL -o "$tmp_dl" "$ASSET_URL"
    chmod +x "$tmp_dl"

    if ! file "$tmp_dl" 2>/dev/null | grep -q 'ELF'; then
        rm -f "$tmp_dl"
        die "downloaded file is not an ELF binary"
    fi

    if [ -f "$BIN_PATH" ]; then
        log "backup old binary -> $BIN_PATH.bak.$TS"
        cp -a "$BIN_PATH" "$BIN_PATH.bak.$TS"
    fi

    log "installing binary to $BIN_PATH"
    mv -f "$tmp_dl" "$BIN_PATH"
    chmod +x "$BIN_PATH"
    log "binary size: $(wc -c < "$BIN_PATH") bytes"
else
    log "skip download, reuse existing $BIN_PATH"
    [ -f "$BIN_PATH" ] || die "--skip-download given but $BIN_PATH does not exist"
fi

# ==================== Generate config ====================
if [ $SKIP_CONFIG -eq 0 ]; then
    CONFIG_DIR="$INSTALL_DIR/instances/$INSTANCE_ID"
    mkdir -p "$CONFIG_DIR"

    log "writing config.yml"
    cat > "$INSTALL_DIR/config.yml" <<CFG_EOF
instances:
    - id: $INSTANCE_ID
      panel:
        url: $PANEL_URL
      kernel:
        type: $KERNEL
        config_dir: $CONFIG_DIR
        log_level: warn
      log:
        level: $LOG_LEVEL
        output: stdout
      health_port: $HEALTH_PORT
      machine:
        machine_id: $MACHINE_ID
        token_env: $TOKEN_ENV_NAME
CFG_EOF
    chmod 600 "$INSTALL_DIR/config.yml"

    log "writing credentials.env"
    printf '%s=%s\n' "$TOKEN_ENV_NAME" "$TOKEN" > "$INSTALL_DIR/credentials.env"
    chmod 600 "$INSTALL_DIR/credentials.env"

    log "writing install-meta.json"
    cat > "$INSTALL_DIR/install-meta.json" <<META_EOF
{
  "config_mode": "instances",
  "version": "latest",
  "latest_instance_id": "$INSTANCE_ID",
  "instance_count": 1,
  "instances": [
    {
      "id": "$INSTANCE_ID",
      "panel_url": "$PANEL_URL",
      "mode": "machine",
      "node_id": null,
      "machine_id": $MACHINE_ID,
      "health_port": $HEALTH_PORT
    }
  ],
  "updated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
META_EOF
    chmod 600 "$INSTALL_DIR/install-meta.json"
else
    log "keeping existing config.yml / credentials.env / install-meta.json"
fi

# ==================== systemd unit ====================
log "writing systemd service unit"
cat > "$SERVICE_FILE" <<'SVC_EOF'
[Unit]
Description=Xboard Node Backend (cert-pin patched)
Documentation=https://github.com/pandanetworkgroup/xboard-node-key
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=/etc/xboard-node
EnvironmentFile=-/etc/xboard-node/credentials.env
ExecStart=/usr/local/bin/xboard-node -c /etc/xboard-node/config.yml
Restart=always
RestartSec=5
LimitNOFILE=1048576
NoNewPrivileges=true
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVC_EOF

systemctl daemon-reload
systemctl enable xboard-node 2>/dev/null || true

# ==================== Start ====================
log "restarting xboard-node service"
systemctl restart xboard-node
sleep 3

if systemctl is-active --quiet xboard-node; then
    log "service is active"
else
    warn "service not active, recent logs:"
    journalctl -u xboard-node -n 30 --no-pager || true
    die "deployment failed"
fi

# ==================== Done ====================
echo
log "============ deployment done ============"
log "instance_id: $INSTANCE_ID"
log "machine_id:  $MACHINE_ID"
log "panel_url:   $PANEL_URL"
log "binary:      $BIN_PATH ($(wc -c < "$BIN_PATH") bytes)"
log "config:      $INSTALL_DIR/config.yml"
echo
log "logs:       journalctl -u xboard-node -f"
log "verify:     wait 60-90s, then check v2_server.cert_fingerprint / cert_pem in panel DB"
log "rollback:   sudo cp $BIN_PATH.bak.* $BIN_PATH && sudo systemctl restart xboard-node"
